version: '2.1'

services:

  users-db:
    container_name: users-db
    build: https://github.com/artdokxxx/flask-microservices-users.git#master:project/db
    ports:
      - 5435:5432 # HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  users-service:
    container_name: users-service
    build: https://github.com/artdokxxx/flask-microservices-users.git
    expose:
      - "5000"
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
    depends_on:
      users-db:
        condition: service_healthy
    links:
      - users-db
    command: gunicorn -b 0.0.0.0:5000 manage:app

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      users-service:
        condition: service_started
    links:
      - users-service
    healthcheck:
      test: ['CMD', "curl", "-f", "http://localhost"]
      interval: 1m30s